name: 'Test with Vader'
description: 'Test your vim plugin with vader.vim'
author: PsychoLlama

branding:
  icon: check-circle
  color: green

inputs:
  test-pattern:
    description: 'A glob which points to your vader test files.'
    required: false
    default: '**/*.vader'
  neovim:
    description: 'Use neovim instead of vim'
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Test with Vader
      shell: bash
      run: $GITHUB_ACTION_PATH/run-vader
      env:
        TEST_PATTERN: ${{ inputs.test-pattern }}
        USE_NEOVIM: ${{ inputs.neovim }}
