#!/usr/bin/env bash
set -euo pipefail

vader_path="${GITHUB_ACTION_PATH:-/tmp/}.vader.vim"
vim_runtime_path="$vader_path"

# Dynamically generate the vim runtime path from user input. Typically this is
# the parent repository, but it could be multiple plugins or plugin globs.
for plugin in $PLUGIN_PATHS; do
  vim_runtime_path+=",$plugin"
done

# Obligatory check for "/after" plugins (see `:help after-directory`)
for plugin in $PLUGIN_PATHS; do
  if [[ -d "$plugin/after" ]]; then
    vim_runtime_path+=",$plugin/after"
  fi
done

# For local testing: don't try to clone the repo twice.
if [[ ! -d "$vader_path" ]]; then
  git clone --depth=1 'https://github.com/junegunn/vader.vim.git' "$vader_path"
fi

vimrc="
filetype off
set runtimepath+=$vim_runtime_path
filetype plugin indent on
"

editor=vim
if [[ ! "${USE_NEOVIM:-}" == false ]]; then
  editor=nvim
fi

# Running in silent Ex mode avoids garbled log output.
# Unfortunately color isn't supported without an interactive vim frontend.
"$editor" -Es -Nu <(echo "$vimrc") -c "Vader! $TEST_PATTERN"
