name: Test
on: push

jobs:
  test:
    name: Test (${{ matrix.editor }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        editor: ['vim', 'neovim']
    steps:
      - uses: actions/checkout@v2
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: ${{ matrix.editor == 'neovim' }}
      - uses: ./
        with:
          neovim: ${{ matrix.editor == 'neovim' }}
